In [1]:
# Import necessary libraries
import time

def convert_length(value, unit):
    #Convert length between meters and feet.
    #param value: Numeric value to be converted
    #param unit: The unit of the input value ('m' for meters, 'ft' for feet)
    #return: Converted value with appropriate unit

    if unit == 'm':
        return value * 3.28084, 'ft'
    elif unit == 'ft':
        return value / 3.28084, 'm'
    else:
        raise ValueError("Unsupported length unit. Use 'm' for meters or 'ft' for feet.")

#Convert weight between kilograms and pounds.
#param value: Numeric value to be converted
#param unit: The unit of the input value ('kg' for kilograms, 'lbs' for pounds)
    #return: Converted value with appropriate unit
def convert_weight(value, unit):


    if unit == 'kg':
        return value * 2.20462, 'lbs'
    elif unit == 'lbs':
        return value / 2.20462, 'kg'
    else:
        raise ValueError("Unsupported weight unit. Use 'kg' for kilograms or 'lbs' for pounds.")

def convert_volume(value, unit):

    #Convert volume between liters and gallons.
    #param value: Numeric value to be converted
    #param unit: The unit of the input value ('L' for liters, 'gal' for gallons)
    #return: Converted value with appropriate unit

    if unit == 'L':
        return value * 0.264172, 'gal'
    elif unit == 'gal':
        return value / 0.264172, 'L'
    else:
        raise ValueError("Unsupported volume unit. Use 'L' for liters or 'gal' for gallons.")

def main():
    print("Unit Converter: Choose a conversion type:")
    print("1. Length (meters to feet / feet to meters)")
    print("2. Weight (kilograms to pounds / pounds to kilograms)")
    print("3. Volume (liters to gallons / gallons to liters)")

    try:
        choice = int(input("Enter your choice (1-3): "))
        value = float(input("Enter the value to convert: "))

        if choice == 1:
            unit = input("Enter the unit (m/ft): ")
            converted_value, converted_unit = convert_length(value, unit)
        elif choice == 2:
            unit = input("Enter the unit (kg/lbs): ")
            converted_value, converted_unit = convert_weight(value, unit)
        elif choice == 3:
            unit = input("Enter the unit (L/gal): ")
            converted_value, converted_unit = convert_volume(value, unit)
        else:
            print("Invalid choice. Please select a valid option.")
            return

        print(f"Converted Value: {converted_value:.2f} {converted_unit}")
    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print("An unexpected error occurred:", e)

if __name__ == "__main__":
    main()

Unit Converter: Choose a conversion type:
1. Length (meters to feet / feet to meters)
2. Weight (kilograms to pounds / pounds to kilograms)
3. Volume (liters to gallons / gallons to liters)
Enter your choice (1-3): 1
Enter the value to convert: 15
Enter the unit (m/ft): m
Converted Value: 49.21 ft


In [5]:
def calculate(numbers, operation):
    #Perform the specified operation on a list of numbers.
    # Check the operation type and calculate the result
    if operation == 'sum':
        return sum(numbers)
    elif operation == 'average':
        return sum(numbers) / len(numbers) if numbers else 0
    elif operation == 'maximum':
        return max(numbers)
    elif operation == 'minimum':
        return min(numbers)

def main():
    #Main function to execute the mathematical operations program.
    # Define the available operations and their display names
    operations = {
        '1': ('sum', 'Sum'),
        '2': ('average', 'Average'),
        '3': ('maximum', 'Maximum'),
        '4': ('minimum', 'Minimum')
    }

    # Prompt user to choose an operation
    print("Choose an operation:")
    for key, (_, name) in operations.items():
        print(f"{key}. {name}")

    # Get the user's choice
    choice = input("Enter the number of the operation: ")
    if choice not in operations:
        print("Invalid choice.")
        return

    try:
        # Take input for numbers and convert them to a list of floats
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))
        if not numbers:
            raise ValueError("The list cannot be empty.")

        # Get the corresponding operation and display the result
        operation = operations[choice][0]
        result = calculate(numbers, operation)
        print(f"The {operations[choice][1]} of the numbers is: {result}")
    except ValueError as e:
        # Handle any errors (e.g., invalid numbers or empty list)
        print(f"Error: {e}")

# Execute the main function when the script is run
if __name__ == "__main__":
    main()


Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter the number of the operation: 1
Enter numbers separated by spaces: 5
The Sum of the numbers is: 5.0


In [6]:
def extract_every_other(lst):
    # Extract every other element from the input list, starting from the first element.
    # This is done using list slicing with a step of 2.
    return lst[::2]

# Example usage
example_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(example_list)

# Print the result to show the output
print(result)  # Output: [1, 3, 5]



[1, 3, 5]


In [7]:
def get_sublist(lst, start, end):
    # Extract a sublist from the given list using the start and end indices.
    # The end index is inclusive, so we add 1 to the end value for slicing.
    return lst[start:end+1]

# Example usage
example_list = [1, 2, 3, 4, 5, 6]

# Get the sublist from index 2 to 4 (inclusive)
result = get_sublist(example_list, 2, 4)

# Print the result to see the sublist
print(result)  # Output: [3, 4, 5]


[3, 4, 5]


In [8]:
def reverse_list(lst):
    # Reverse the given list using slicing.
    # The slicing step of -1 means "start from the end and move backwards."
    return lst[::-1]

# Example usage
example_list = [1, 2, 3, 4, 5]

# Reverse the list and store the result
result = reverse_list(example_list)

# Print the reversed list
print(result)  # Output: [5, 4, 3, 2, 1]


[5, 4, 3, 2, 1]


In [10]:
def remove_first_last(lst):
    # Remove the first and last elements of the list using slicing.
    # The slice starts from index 1 (second element) and goes up to the second last element.
    return lst[1:-1]

# Example usage
example_list = [1, 2, 3, 4, 5]

# Call the function and store the result
result = remove_first_last(example_list)

# Print the result, which will be a list without the first and last elements
print(result)  # Output: [2, 3, 4]


[2, 3, 4]


In [11]:
def get_first_n(lst, n):
    # Extract the first n elements from the list using slicing.
    # The slice starts from the beginning of the list and ends at index n.
    return lst[:n]

# Example usage
example_list = [1, 2, 3, 4, 5]

# Call the function to get the first 3 elements of the list
result = get_first_n(example_list, 3)

# Print the result, which will be the first 3 elements of the list
print(result)


[1, 2, 3]


In [12]:
#Task8
def get_last_n(lst, n):
    """
    Extracts the last n elements from the given list.

    Parameters:
    lst (list): The input list from which the last n elements are to be extracted.
    n (int): The number of elements to extract from the end of the list.

    Returns:
    list: A new list containing the last n elements of the original list.
    """
    return lst[-n:]  # Slice to get the last n elements

# Example usage
example_list = [1, 2, 3, 4, 5]
result = get_last_n(example_list, 2)
print(result)  # Output: [4, 5]


[4, 5]


In [ ]:
#Task- 9
def reverse_skip(lst):
    """
    Extracts elements in reverse order starting from the second-to-last element,
    skipping one element in between.

    Parameters:
    lst (list): The input list from which elements are to be extracted.

    Returns:
    list: A new list containing every second element starting from the second-to-last element, moving backward.
    """
    return lst[-2::-2]  # Slice to start from second-to-last and skip every second element backward

# Example usage
example_list = [1, 2, 3, 4, 5, 6]
result = reverse_skip(example_list)
print(result)


[5, 3, 1]


In [13]:
def flatten(lst):
    flat_list = []  # Initialize an empty list to store flattened elements
    for item in lst:
        if isinstance(item, list):  # Check if the item is a list
            flat_list.extend(flatten(item))  # Recursively flatten nested lists
        else:
            flat_list.append(item)  # If it's not a list, add it directly
    return flat_list

# Example usage
example_list = [[1, 2], [3, [4, 5]], [6, 7]]
result = flatten(example_list)
print(result)


[1, 2, 3, 4, 5, 6, 7]


In [14]:
#Task-11
def access_nested_element(lst, indices):

    #Extracts a specific element from a nested list given a list of indices.

    #Parameters:
    #lst (list): The nested list from which to extract the element.
    #indices (list): A list of indices representing the path to the desired element.

    #Returns:
    #any: The element at the specified indices, or None if indices are invalid.

    try:
        element = lst  # Start with the original nested list
        for index in indices:
            element = element[index]  # Navigate deeper using the provided indices
        return element
    except (IndexError, TypeError):
        return None  # Return None if indices are out of range or invalid

# Example usage
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
result = access_nested_element(nested_list, [1, 2])
print(result)


6


In [15]:
def sum_nested(lst):
    total = 0
    for element in lst:
        if isinstance(element, list):
            total += sum_nested(element)
        else:
            total += element
    return total

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(result)  # Output will be 21


21


In [16]:
def remove_element(lst, elem):
    result = []  # Initialize an empty list to store the filtered elements
    for item in lst:
        if isinstance(item, list):  # If the item is a sublist, we process it recursively
            new_sublist = remove_element(item, elem)  # Call the function recursively on the sublist
            result.append(new_sublist)  # Append the processed sublist to the result
        elif item != elem:  # If the current item is not equal to the element to be removed, add it to the result
            result.append(item)
    return result  # Return the modified list after all elements are processed

# Example usage
nested_list = [[1, 2], [3, 2], [4, 5]]
result = remove_element(nested_list, 2)  # Remove all occurrences of 2
print(result)  # Output will be [[1], [3], [4, 5]]


[[1], [3], [4, 5]]


In [17]:
def find_max(lst):
    max_value = float('-inf')  # Start with a very small value (negative infinity) to ensure any number is larger

    for item in lst:
        if isinstance(item, list):  # If the item is a sublist, we process it recursively
            max_value = max(max_value, find_max(item))  # Compare the current max with the max from the sublist
        else:  # If the item is a number, just compare it with the current max_value
            max_value = max(max_value, item)

    return max_value  # Return the maximum value found

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)  # Find the maximum value in the nested list
print(result)  # Output will be 6


6


In [18]:
def count_occurrences(lst, elem):
    count = 0  # Start with a count of zero

    for item in lst:
        if isinstance(item, list):  # If the item is a sublist, we process it recursively
            count += count_occurrences(item, elem)  # Add the count from the sublist
        elif item == elem:  # If the item matches the element we're counting
            count += 1  # Increase the count

    return count  # Return the total count

# Example usage
nested_list = [[1, 2], [2, 3], [2, 4]]
result = count_occurrences(nested_list, 2)  # Count how many times 2 appears
print(result)  # Output will be 3


3


In [19]:
def deep_flatten(lst):
    flattened_list = []  # Initialize an empty list to store the flattened items

    for item in lst:
        if isinstance(item, list):  # If the item is a sublist, we process it recursively
            flattened_list.extend(deep_flatten(item))  # Add all items from the sublist to the flattened list
        else:  # If the item is not a list, simply add it to the flattened list
            flattened_list.append(item)

    return flattened_list  # Return the fully flattened list

# Example usage
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)  # Flatten the deeply nested list
print(result)  # Output will be [1, 2, 3, 4, 5, 6, 7, 8]


[1, 2, 3, 4, 5, 6, 7, 8]


In [20]:
def average_nested(lst):
    def flatten_and_sum(lst):
        total_sum = 0  # Initialize the total sum of elements
        count = 0  # Initialize the count of elements

        for item in lst:
            if isinstance(item, list):  # If the item is a sublist, process it recursively
                sub_sum, sub_count = flatten_and_sum(item)  # Get the sum and count from the sublist
                total_sum += sub_sum  # Add the sum of the sublist to the total sum
                count += sub_count  # Add the count of the sublist to the total count
            else:
                total_sum += item  # If it's a number, add it to the sum
                count += 1  # Increase the count by 1

        return total_sum, count  # Return the total sum and count of elements

    total, count = flatten_and_sum(lst)  # Get the total sum and count from the entire list
    return total / count if count > 0 else 0  # Calculate and return the average, avoid division by zero

# Example usage
nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)  # Calculate the average of the nested list
print(result)  # Output will be 3.5


3.5


In [21]:
import numpy as np

def create_empty_array():
    # Creates a 2x2 uninitialized (empty) NumPy array
    return np.empty((2, 2))

def create_ones_array():
    # Creates a 4x2 NumPy array filled with ones
    return np.ones((4, 2))

def create_filled_array(shape, value):
    # Creates a NumPy array of a specified shape, filled with a given value
    return np.full(shape, value)

def create_zeros_like(reference_array):
    # Creates a NumPy array of zeros with the same shape and type as the given reference array
    return np.zeros_like(reference_array)

def create_ones_like(reference_array):
    # Creates a NumPy array of ones with the same shape and type as the given reference array
    return np.ones_like(reference_array)

def convert_list_to_numpy(new_list):
    # Converts a Python list into a NumPy array
    return np.array(new_list)

# Example Usage
empty_array = create_empty_array()
print("Empty Array (2x2):\n", empty_array)  # Print the empty 2x2 array

ones_array = create_ones_array()
print("\nAll Ones Array (4x2):\n", ones_array)  # Print a 4x2 array filled with ones

filled_array = create_filled_array((3, 3), 7)  # Example: Filling a 3x3 array with 7
print("\nArray Filled with 7 (3x3):\n", filled_array)  # Print a 3x3 array filled with 7

# Create a reference array for comparison
reference_array = np.array([[5, 6, 7], [8, 9, 10]])

zeros_like_array = create_zeros_like(reference_array)
print("\nZeros Array with Same Shape as Reference:\n", zeros_like_array)  # Print a zero-filled array with the same shape as reference

ones_like_array = create_ones_like(reference_array)
print("\nOnes Array with Same Shape as Reference:\n", ones_like_array)  # Print a ones-filled array with the same shape as reference

new_list = [1, 2, 3, 4]  # A sample Python list
numpy_array = convert_list_to_numpy(new_list)
print("\nConverted NumPy Array:\n", numpy_array)  # Print the NumPy array created from the list


Empty Array (2x2):
 [[3.18746694e-316 0.00000000e+000]
 [9.88131292e-324             nan]]

All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array Filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array with Same Shape as Reference:
 [[0 0 0]
 [0 0 0]]

Ones Array with Same Shape as Reference:
 [[1 1 1]
 [1 1 1]]

Converted NumPy Array:
 [1 2 3 4]


In [22]:
import numpy as np

def create_range_array():
    # Creates an array with values ranging from 10 to 49
    return np.arange(10, 50)

def create_3x3_matrix():
    # Creates a 3x3 matrix with values ranging from 0 to 8
    return np.arange(9).reshape(3, 3)

def create_identity_matrix():
    # Creates a 3x3 identity matrix (diagonal elements are 1, others are 0)
    return np.eye(3)

def create_random_array_mean():
    # Creates a random array of size 30 and calculates its mean value
    random_array = np.random.random(30)  # Generate random values between 0 and 1
    mean_value = random_array.mean()  # Calculate the mean of the array
    return random_array, mean_value

def create_10x10_random_min_max():
    # Creates a 10x10 matrix with random values and calculates its min and max values
    random_matrix = np.random.random((10, 10))  # Generate a 10x10 matrix of random values
    min_value = random_matrix.min()  # Find the minimum value in the matrix
    max_value = random_matrix.max()  # Find the maximum value in the matrix
    return random_matrix, min_value, max_value

def replace_fifth_element():
    # Creates a zero array of size 10 and replaces the 5th element (index 4) with 1
    arr = np.zeros(10)  # Create an array of zeros of length 10
    arr[4] = 1  # Replace the 5th element (index 4) with 1
    return arr

def reverse_array():
    # Reverses the given array
    arr = np.array([1, 2, 0, 0, 4, 0])  # Create an example array
    return arr[::-1]  # Reverse the array using slicing

def create_border_array():
    # Creates a 5x5 array with 1s on the border and 0s in the middle
    arr = np.ones((5, 5))  # Create a 5x5 array filled with ones
    arr[1:-1, 1:-1] = 0  # Set the inner elements (excluding the border) to 0
    return arr

def create_checkerboard_pattern():
    # Creates an 8x8 matrix and fills it with a checkerboard pattern
    checkerboard = np.zeros((8, 8), dtype=int)  # Create an 8x8 matrix of zeros
    checkerboard[1::2, ::2] = 1  # Fill alternating rows with 1s (even rows, odd columns)
    checkerboard[::2, 1::2] = 1  # Fill alternating columns with 1s (odd rows, even columns)
    return checkerboard

# Example Usage
print("Array with values from 10 to 49:\n", create_range_array())

print("\n3x3 Matrix with values 0 to 8:\n", create_3x3_matrix())

print("\n3x3 Identity Matrix:\n", create_identity_matrix())

random_array, mean_value = create_random_array_mean()
print("\nRandom Array of Size 30:\n", random_array)
print("Mean Value:", mean_value)

random_matrix, min_value, max_value = create_10x10_random_min_max()
print("\n10x10 Random Matrix:\n", random_matrix)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

print("\nZero Array with 5th Element as 1:\n", replace_fifth_element())

print("\nReversed Array:\n", reverse_array())

print("\n2D Array with Border 1s and Inside 0s:\n", create_border_array())

print("\n8x8 Checkerboard Pattern:\n", create_checkerboard_pattern())


Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of Size 30:
 [0.01333648 0.26059319 0.59688882 0.58026702 0.7262361  0.97031148
 0.55308213 0.34032373 0.66362183 0.2846089  0.08540317 0.1942923
 0.92112599 0.7086513  0.18833402 0.72355686 0.3276765  0.1307434
 0.70898455 0.01908997 0.29768543 0.46098867 0.21631813 0.37812149
 0.04263607 0.53627301 0.16925032 0.07557906 0.52568875 0.36332303]
Mean Value: 0.4020997240357179

10x10 Random Matrix:
 [[0.75095851 0.64723479 0.03930894 0.6194913  0.17759121 0.15474742
  0.03597584 0.40573467 0.32619309 0.02910749]
 [0.65142514 0.15914433 0.20023191 0.76569612 0.57088622 0.89148518
  0.56365959 0.06455217 0.67728791 0.99710714]
 [0.10862749 0.41923195 0.27167851 0.2867035  0.21394342 0.14773518
  0.47675

In [24]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])  # A 2x2 array
y = np.array([[5, 6], [7, 8]])  # Another 2x2 array
v = np.array([9, 10])  # A 1D array of size 2
w = np.array([11, 12])  # Another 1D array of size 2

# 1. Add the two arrays
def add_arrays(x, y):
    """
    Adds two 2D numpy arrays element-wise.

    Args:
    x (numpy.ndarray): First 2D array.
    y (numpy.ndarray): Second 2D array.

    Returns:
    numpy.ndarray: Resultant array from element-wise addition of x and y.
    """
    return x + y  # Add corresponding elements of x and y

add_result = add_arrays(x, y)
print("Addition of x and y:\n", add_result)

# 2. Subtract the two arrays
def subtract_arrays(x, y):
    """
    Subtracts the second array (y) from the first array (x) element-wise.

    Args:
    x (numpy.ndarray): First 2D array.
    y (numpy.ndarray): Second 2D array.

    Returns:
    numpy.ndarray: Resultant array from element-wise subtraction of x and y.
    """
    return x - y  # Subtract corresponding elements of y from x

sub_result = subtract_arrays(x, y)
print("\nSubtraction of x and y:\n", sub_result)

# 3. Multiply the array with any integers of your choice (let's use 2 for demonstration)
def multiply_array(x, scalar):
    """
    Multiplies each element of the 2D numpy array x by a scalar value.

    Args:
    x (numpy.ndarray): A 2D numpy array.
    scalar (int): Scalar value to multiply each element of the array by.

    Returns:
    numpy.ndarray: A new numpy array with elements multiplied by scalar.
    """
    return x * scalar  # Multiply each element of x by scalar

mul_result = multiply_array(x, 2)
print("\nMultiplying x by 2:\n", mul_result)

# 4. Find the square of each element of the array
def square_elements(x):
    """
    Computes the square of each element in the 2D numpy array x.

    Args:
    x (numpy.ndarray): A 2D numpy array.

    Returns:
    numpy.ndarray: A new array with each element squared.
    """
    return np.square(x)  # Square each element of x

square_result = square_elements(x)
print("\nSquare of each element in x:\n", square_result)

# 5. Find the dot product between: v and w, x and v, x and y
def dot_product(a, b):
    """
    Computes the dot product between two numpy arrays.

    Args:
    a (numpy.ndarray): First array.
    b (numpy.ndarray): Second array.

    Returns:
    int or numpy.ndarray: Dot product of a and b.
    """
    return np.dot(a, b)  # Compute the dot product of a and b

# v and w (1D arrays)
dot_vw = dot_product(v, w)
print("\nDot product between v and w:", dot_vw)

# x and v (2D and 1D arrays)
dot_xv = dot_product(x, v)
print("\nDot product between x and v:\n", dot_xv)

# x and y (2D arrays)
dot_xy = dot_product(x, y)
print("\nDot product between x and y:\n", dot_xy)

# 6. Concatenate x and y along row (axis=0), and v and w along columns (axis=1)
def concatenate_arrays(x, y, axis):
    """
    Concatenates two numpy arrays along the specified axis.

    Args:
    x (numpy.ndarray): First array.
    y (numpy.ndarray): Second array.
    axis (int): Axis along which to concatenate (0 for rows, 1 for columns).

    Returns:
    numpy.ndarray: Concatenated array.
    """
    return np.concatenate((x, y), axis=axis)  # Concatenate x and y along the given axis

# Concatenate x and y along row (axis=0)
concat_xy_row = concatenate_arrays(x, y, axis=0)
print("\nConcatenating x and y along row:\n", concat_xy_row)

# Concatenate v and w along column (axis=1) - reshaping v and w to be 2D
concat_vw_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("\nConcatenating v and w along column:\n", concat_vw_col)

# 7. Concatenate x and v (observe and explain the error)
def try_concatenate_x_and_v(x, v):
    """
    Tries to concatenate x (2D array) and v (1D array) along columns (axis=1).
    If it fails, the error is caught and returned.

    Args:
    x (numpy.ndarray): A 2D numpy array.
    v (numpy.ndarray): A 1D numpy array.

    Returns:
    str: Error message if concatenation fails.
    """
    try:
        # Attempting to concatenate x and v along columns (axis=1)
        return np.concatenate((x, v), axis=1)
    except Exception as e:
        return str(e)  # Return the error message if it fails

# Trying to concatenate x and v
error_message = try_concatenate_x_and_v(x, v)
print("\nError when trying to concatenate x and v:", error_message)


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplying x by 2:
 [[ 2  4]
 [ 6 10]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product between v and w: 219

Dot product between x and v:
 [29 77]

Dot product between x and y:
 [[19 22]
 [50 58]]

Concatenating x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenating v and w along column:
 [[ 9 11]
 [10 12]]

Error when trying to concatenate x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [25]:
import numpy as np

# Define the arrays
A = np.array([[3, 4], [7, 8]])  # 2x2 matrix A
B = np.array([[5, 3], [2, 1]])  # 2x2 matrix B

# 1. Prove A.A⁻¹ = I (Identity Matrix)
def prove_identity(A):
    """
    Proves that A * A⁻¹ = Identity matrix.

    Args:
    A (numpy.ndarray): A square matrix.

    Returns:
    numpy.ndarray: Identity matrix.
    """
    A_inv = np.linalg.inv(A)  # Inverse of A
    I = np.dot(A, A_inv)  # Matrix multiplication of A and A⁻¹
    return I

identity_matrix = prove_identity(A)
print("A * A⁻¹ (Identity Matrix):\n", identity_matrix)

# 2. Prove AB ≠ BA (Matrix multiplication is not commutative)
def prove_non_commutative(A, B):
    """
    Proves that AB ≠ BA.

    Args:
    A (numpy.ndarray): Matrix A.
    B (numpy.ndarray): Matrix B.

    Returns:
    tuple: AB and BA results.
    """
    AB = np.dot(A, B)
    BA = np.dot(B, A)
    return AB, BA

AB, BA = prove_non_commutative(A, B)
print("\nAB = \n", AB)
print("BA = \n", BA)
print("\nAB ≠ BA: ", not np.array_equal(AB, BA))

# 3. Prove (AB)ᵀ = BᵀAᵀ (Transpose of a product)
def prove_transpose_product(A, B):
    """
    Proves that (AB)ᵀ = BᵀAᵀ.

    Args:
    A (numpy.ndarray): Matrix A.
    B (numpy.ndarray): Matrix B.

    Returns:
    tuple: (AB)ᵀ and BᵀAᵀ results.
    """
    AB_transpose = np.transpose(np.dot(A, B))
    B_transpose_A_transpose = np.dot(np.transpose(B), np.transpose(A))
    return AB_transpose, B_transpose_A_transpose

AB_transpose, B_transpose_A_transpose = prove_transpose_product(A, B)
print("\n(AB)ᵀ = \n", AB_transpose)
print("BᵀAᵀ = \n", B_transpose_A_transpose)
print("\n(AB)ᵀ = BᵀAᵀ: ", np.array_equal(AB_transpose, B_transpose_A_transpose))

# 4. Solve the system of linear equations using Inverse Method
# System of equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent the system in matrix form: AX = B
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficient matrix A
B_matrix = np.array([-1, -3, 9])  # Constants vector B

# Solve for X using inverse method: X = A⁻¹ * B
def solve_linear_system(A_matrix, B_matrix):
    """
    Solves the linear system of equations using inverse method.

    Args:
    A_matrix (numpy.ndarray): Coefficient matrix.
    B_matrix (numpy.ndarray): Constants vector.

    Returns:
    numpy.ndarray: Solution vector X (values for x, y, z).
    """
    A_inv = np.linalg.inv(A_matrix)  # Inverse of matrix A
    X = np.dot(A_inv, B_matrix)  # Solving for X
    return X

solution = solve_linear_system(A_matrix, B_matrix)
print("\nSolution for the system of equations (using inverse method):", solution)

# 5. Solve the system of linear equations using np.linalg.inv function directly
def solve_using_linalg(A_matrix, B_matrix):
    """
    Solves the linear system of equations using np.linalg.inv directly.

    Args:
    A_matrix (numpy.ndarray): Coefficient matrix.
    B_matrix (numpy.ndarray): Constants vector.

    Returns:
    numpy.ndarray: Solution vector X.
    """
    X_linalg = np.linalg.solve(A_matrix, B_matrix)  # Using np.linalg.solve to solve AX = B
    return X_linalg

solution_linalg = solve_using_linalg(A_matrix, B_matrix)
print("\nSolution using np.linalg.solve:", solution_linalg)


A * A⁻¹ (Identity Matrix):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]

AB ≠ BA:  True

(AB)ᵀ = 
 [[23 51]
 [13 29]]
BᵀAᵀ = 
 [[23 51]
 [13 29]]

(AB)ᵀ = BᵀAᵀ:  True

Solution for the system of equations (using inverse method): [ 2.  1. -2.]

Solution using np.linalg.solve: [ 2.  1. -2.]


In [ ]:
import numpy as np

# Define the arrays
A = np.array([[3, 4], [7, 8]])  # 2x2 matrix A
B = np.array([[5, 3], [2, 1]])  # 2x2 matrix B

# 1. Prove A.A⁻¹ = I (Identity Matrix)
def prove_identity(A):
    """
    Proves that A * A⁻¹ = Identity matrix.

    Args:
    A (numpy.ndarray): A square matrix.

    Returns:
    numpy.ndarray: Identity matrix.
    """
    A_inv = np.linalg.inv(A)  # Inverse of A
    I = np.dot(A, A_inv)  # Matrix multiplication of A and A⁻¹
    return I

identity_matrix = prove_identity(A)
print("A * A⁻¹ (Identity Matrix):\n", identity_matrix)

# 2. Prove AB ≠ BA (Matrix multiplication is not commutative)
def prove_non_commutative(A, B):
    """
    Proves that AB ≠ BA.

    Args:
    A (numpy.ndarray): Matrix A.
    B (numpy.ndarray): Matrix B.

    Returns:
    tuple: AB and BA results.
    """
    AB = np.dot(A, B)
    BA = np.dot(B, A)
    return AB, BA

AB, BA = prove_non_commutative(A, B)
print("\nAB = \n", AB)
print("BA = \n", BA)
print("\nAB ≠ BA: ", not np.array_equal(AB, BA))

# 3. Prove (AB)ᵀ = BᵀAᵀ (Transpose of a product)
def prove_transpose_product(A, B):
    """
    Proves that (AB)ᵀ = BᵀAᵀ.

    Args:
    A (numpy.ndarray): Matrix A.
    B (numpy.ndarray): Matrix B.

    Returns:
    tuple: (AB)ᵀ and BᵀAᵀ results.
    """
    AB_transpose = np.transpose(np.dot(A, B))
    B_transpose_A_transpose = np.dot(np.transpose(B), np.transpose(A))
    return AB_transpose, B_transpose_A_transpose

AB_transpose, B_transpose_A_transpose = prove_transpose_product(A, B)
print("\n(AB)ᵀ = \n", AB_transpose)
print("BᵀAᵀ = \n", B_transpose_A_transpose)
print("\n(AB)ᵀ = BᵀAᵀ: ", np.array_equal(AB_transpose, B_transpose_A_transpose))

# 4. Solve the system of linear equations using Inverse Method
# System of equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent the system in matrix form: AX = B
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficient matrix A
B_matrix = np.array([-1, -3, 9])  # Constants vector B

# Solve for X using inverse method: X = A⁻¹ * B
def solve_linear_system(A_matrix, B_matrix):
    """
    Solves the linear system of equations using inverse method.

    Args:
    A_matrix (numpy.ndarray): Coefficient matrix.
    B_matrix (numpy.ndarray): Constants vector.

    Returns:
    numpy.ndarray: Solution vector X (values for x, y, z).
    """
    A_inv = np.linalg.inv(A_matrix)  # Inverse of matrix A
    X = np.dot(A_inv, B_matrix)  # Solving for X
    return X

solution = solve_linear_system(A_matrix, B_matrix)
print("\nSolution for the system of equations (using inverse method):", solution)

# 5. Solve the system of linear equations using np.linalg.solve function directly
def solve_using_linalg(A_matrix, B_matrix):
    """
    Solves the linear system of equations using np.linalg.inv directly.

    Args:
    A_matrix (numpy.ndarray): Coefficient matrix.
    B_matrix (numpy.ndarray): Constants vector.

    Returns:
    numpy.ndarray: Solution vector X.
    """
    X_linalg = np.linalg.solve(A_matrix, B_matrix)  # Using np.linalg.solve to solve AX = B
    return X_linalg

solution_linalg = solve_using_linalg(A_matrix, B_matrix)
print("\nSolution using np.linalg.solve:", solution_linalg)


A * A⁻¹ (Identity Matrix):
 [[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]

AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]

AB ≠ BA:  True

(AB)ᵀ = 
 [[23 51]
 [13 29]]
BᵀAᵀ = 
 [[23 51]
 [13 29]]

(AB)ᵀ = BᵀAᵀ:  True

Solution for the system of equations (using inverse method): [ 2.  1. -2.]

Solution using np.linalg.solve: [ 2.  1. -2.]


In [9]:
import time
import numpy as np

# Create two lists/arrays of size 1,000,000
size = 1000000
list1 = [i for i in range(size)]  # Create a list with values from 0 to 999,999
list2 = [i for i in range(size)]  # Create another list with values from 0 to 999,999

# 1. Element-wise Addition
# Using Python lists
start_time = time.time()  # Record start time
list_add = [list1[i] + list2[i] for i in range(size)]  # Add corresponding elements from both lists
print("Time taken for element-wise addition with Python lists: {:.6f} seconds".format(time.time() - start_time))  # Print time taken

# Using NumPy arrays
np_array1 = np.arange(size)  # Create a NumPy array with values from 0 to 999,999
np_array2 = np.arange(size)  # Create another NumPy array with values from 0 to 999,999
start_time = time.time()  # Record start time
np_add = np_array1 + np_array2  # Add corresponding elements from both NumPy arrays
print("Time taken for element-wise addition with NumPy arrays: {:.6f} seconds".format(time.time() - start_time))  # Print time taken

# 2. Element-wise Multiplication
# Using Python lists
start_time = time.time()  # Record start time
list_multiply = [list1[i] * list2[i] for i in range(size)]  # Multiply corresponding elements from both lists
print("Time taken for element-wise multiplication with Python lists: {:.6f} seconds".format(time.time() - start_time))  # Print time taken

# Using NumPy arrays
start_time = time.time()  # Record start time
np_multiply = np_array1 * np_array2  # Multiply corresponding elements from both NumPy arrays
print("Time taken for element-wise multiplication with NumPy arrays: {:.6f} seconds".format(time.time() - start_time))  # Print time taken

# 3. Dot Product
# Using Python lists
start_time = time.time()  # Record start time
dot_product_list = sum(list1[i] * list2[i] for i in range(size))  # Calculate the dot product of the two lists
print("Time taken for dot product with Python lists: {:.6f} seconds".format(time.time() - start_time))  # Print time taken

# Using NumPy arrays
start_time = time.time()  # Record start time
dot_product_np = np.dot(np_array1, np_array2)  # Calculate the dot product using NumPy
print("Time taken for dot product with NumPy arrays: {:.6f} seconds".format(time.time() - start_time))  # Print time taken

# 4. Matrix Multiplication (1000x1000)
# Create two matrices of size 1000x1000 using lists
matrix1 = [[i for i in range(1000)] for j in range(1000)]  # 1000x1000 matrix with values from 0 to 999
matrix2 = [[i for i in range(1000)] for j in range(1000)]  # Another 1000x1000 matrix with values from 0 to 999

# Using Python lists
start_time = time.time()  # Record start time
matrix_multiply_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]  # Matrix multiplication using lists
print("Time taken for matrix multiplication with Python lists: {:.6f} seconds".format(time.time() - start_time))  # Print time taken

# Using NumPy arrays
np_matrix1 = np.arange(1000000).reshape(1000, 1000)  # Create a 1000x1000 NumPy matrix
np_matrix2 = np.arange(1000000).reshape(1000, 1000)  # Create another 1000x1000 NumPy matrix
start_time = time.time()  # Record start time
matrix_multiply_np = np.dot(np_matrix1, np_matrix2)  # Perform matrix multiplication using NumPy
print("Time taken for matrix multiplication with NumPy arrays: {:.6f} seconds".format(time.time() - start_time))  # Print time taken


Time taken for element-wise addition with Python lists: 0.081678 seconds
Time taken for element-wise addition with NumPy arrays: 0.007141 seconds
Time taken for element-wise multiplication with Python lists: 0.098190 seconds
Time taken for element-wise multiplication with NumPy arrays: 0.004750 seconds
Time taken for dot product with Python lists: 0.097122 seconds
Time taken for dot product with NumPy arrays: 0.001960 seconds
Time taken for matrix multiplication with Python lists: 180.311425 seconds
Time taken for matrix multiplication with NumPy arrays: 2.522545 seconds
