In [1]:
def meters_to_feet(meters):
    """Convert meters to feet.
    
    Parameters:
        meters (float): The length in meters.
    
    Returns:
        float: The equivalent length in feet.
    """
    return meters * 3.28084

def feet_to_meters(feet):
    """Convert feet to meters.
    
    Parameters:
        feet (float): The length in feet.
    
    Returns:
        float: The equivalent length in meters.
    """
    return feet / 3.28084

def kg_to_lbs(kg):
    """Convert kilograms to pounds.
    
    Parameters:
        kg (float): The weight in kilograms.
    
    Returns:
        float: The equivalent weight in pounds.
    """
    return kg * 2.20462

def lbs_to_kg(lbs):
    """Convert pounds to kilograms.
    
    Parameters:
        lbs (float): The weight in pounds.
    
    Returns:
        float: The equivalent weight in kilograms.
    """
    return lbs / 2.20462

def liters_to_gallons(liters):
    """Convert liters to gallons.
    
    Parameters:
        liters (float): The volume in liters.
    
    Returns:
        float: The equivalent volume in gallons.
    """
    return liters * 0.264172

def gallons_to_liters(gallons):
    """Convert gallons to liters.
    
    Parameters:
        gallons (float): The volume in gallons.
    
    Returns:
        float: The equivalent volume in liters.
    """
    return gallons / 0.264172

def main():
    """Main function to prompt user for conversion type and value."""
    print("Choose a conversion type:")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")
    
    choice = input("Enter the number of your choice: ")
    
    if choice == '1':
        conversion_func = meters_to_feet
        conversion_name = "Meters to Feet"
    elif choice == '2':
        conversion_func = feet_to_meters
        conversion_name = "Feet to Meters"
    elif choice == '3':
        conversion_func = kg_to_lbs
        conversion_name = "Kilograms to Pounds"
    elif choice == '4':
        conversion_func = lbs_to_kg
        conversion_name = "Pounds to Kilograms"
    elif choice == '5':
        conversion_func = liters_to_gallons
        conversion_name = "Liters to Gallons"
    elif choice == '6':
        conversion_func = gallons_to_liters
        conversion_name = "Gallons to Liters"
    else:
        print("Invalid choice. Please select a valid option.")
        return
    
    try:
        value = float(input("Enter the value to convert: "))
        result = conversion_func(value)
        print(f"{value} converted using {conversion_name} is {result:.4f}")
    except ValueError:
        print("Invalid input. Please enter a numeric value.")

main()



Choose a conversion type:
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter the number of your choice: 1
Enter the value to convert: 4
4.0 converted using Meters to Feet is 13.1234


In [2]:
def find_sum(numbers):
    """
    Function to find the sum of a list of numbers.
    
    Parameters:
    numbers (list): A list of numeric values.
    
    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Function to find the average of a list of numbers.
    
    Parameters:
    numbers (list): A list of numeric values.
    
    Returns:
    float: The average of the numbers.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot compute the average of an empty list.")
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Function to find the maximum number in a list.
    
    Parameters:
    numbers (list): A list of numeric values.
    
    Returns:
    float: The maximum number.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find the maximum of an empty list.")
    return max(numbers)


def find_minimum(numbers):
    """
    Function to find the minimum number in a list.
    
    Parameters:
    numbers (list): A list of numeric values.
    
    Returns:
    float: The minimum number.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find the minimum of an empty list.")
    return min(numbers)


def main():
    print("Select an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")
    
    try:
        choice = int(input("Enter the number corresponding to your choice: "))
        
        # Check if the choice is valid
        if choice not in [1, 2, 3, 4]:
            raise ValueError("Invalid choice! Please select a valid operation.")
        
        numbers_input = input("Enter a list of numbers separated by spaces: ")
        
        # Convert input to a list of numbers
        numbers = [float(x) for x in numbers_input.split()]
        
        if len(numbers) == 0:
            raise ValueError("The list of numbers cannot be empty.")
        
        # Perform the selected operation
        if choice == 1:
            result = find_sum(numbers)
            print(f"The sum of the numbers is: {result}")
        elif choice == 2:
            result = find_average(numbers)
            print(f"The average of the numbers is: {result}")
        elif choice == 3:
            result = find_maximum(numbers)
            print(f"The maximum number is: {result}")
        elif choice == 4:
            result = find_minimum(numbers)
            print(f"The minimum number is: {result}")
    
    except ValueError as ve:
        print(f"Error: {ve}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

main()

    
    

Select an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter the number corresponding to your choice: 3
Enter a list of numbers separated by spaces: 1 2 3
The maximum number is: 3.0


In [4]:
# Extract Every Other Element:

def extract_every_other(lst):
    """
    Function to extract every other element from a list, starting from the first element.
    
    Parameters:
    lst (list): A list of elements.
    
    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]

lst = [1, 2, 3, 4, 5, 6]
print(extract_every_other(lst))  # Output: [1, 3, 5]


[1, 3, 5]


In [5]:
# Slice a Sublist:

def get_sublist(lst, start, end):
    """
    Function to return a sublist from the given list, starting from start index and ending at end index (inclusive).
    
    Parameters:
    lst (list): A list of elements.
    start (int): The start index.
    end (int): The end index.
    
    Returns:
    list: The sublist from start to end (inclusive).
    """
    return lst[start:end+1]

lst = [1, 2, 3, 4, 5, 6]
print(get_sublist(lst, 2, 4))  # Output: [3, 4, 5]


[3, 4, 5]


In [6]:
#Reverse a List Using Slicing:

def reverse_list(lst):
    """
    Function to reverse a list using slicing.
    
    Parameters:
    lst (list): A list of elements.
    
    Returns:
    list: The reversed list.
    """
    return lst[::-1]

lst = [1, 2, 3, 4, 5]
print(reverse_list(lst))  # Output: [5, 4, 3, 2, 1]


[5, 4, 3, 2, 1]


In [7]:
#Remove the First and Last Elements:

def remove_first_last(lst):
    """
    Function to remove the first and last elements of a list and return the resulting sublist.
    
    Parameters:
    lst (list): A list of elements.
    
    Returns:
    list: A sublist with the first and last elements removed.
    """
    return lst[1:-1]

lst = [1, 2, 3, 4, 5]
print(remove_first_last(lst))  # Output: [2, 3, 4]


[2, 3, 4]


In [8]:
#Get the First n Elements:
def get_first_n(lst, n):
    """
    Function to extract the first n elements from a list.
    
    Parameters:
    lst (list): A list of elements.
    n (int): The number of elements to extract.
    
    Returns:
    list: The first n elements from the list.
    """
    return lst[:n]

lst = [1, 2, 3, 4, 5]
print(get_first_n(lst, 3))  # Output: [1, 2, 3]


[1, 2, 3]


In [9]:
#Extract Elements from the End:

def get_last_n(lst, n):
    """
    Function to extract the last n elements from a list using slicing.
    
    Parameters:
    lst (list): A list of elements.
    n (int): The number of elements to extract from the end.
    
    Returns:
    list: The last n elements from the list.
    """
    return lst[-n:]

lst = [1, 2, 3, 4, 5]
print(get_last_n(lst, 2))  # Output: [4, 5]


[4, 5]


In [10]:
#Extract Elements in Reverse Order:
    
def reverse_skip(lst):
    """
    Function to extract a list of elements in reverse order, starting from the second-to-last element,
    skipping one element in between.
    
    Parameters:
    lst (list): A list of elements.
    
    Returns:
    list: A new list containing every second element starting from the second-to-last, moving backward.
    """
    return lst[-2::-2]

lst = [1, 2, 3, 4, 5, 6]
print(reverse_skip(lst))  # Output: [5, 3, 1]


[5, 3, 1]


In [11]:
#Flatten a Nested List:
def flatten(lst):
    """
    Function to flatten a nested list into a single list, where all the elements are in a single dimension.
    
    Parameters:
    lst (list): A nested list of elements.
    
    Returns:
    list: A flattened list with all elements in a single dimension.
    """
    flattened = []
    for item in lst:
        if isinstance(item, list):
            flattened.extend(flatten(item))  # Recursively flatten sublist
        else:
            flattened.append(item)
    return flattened

nested_lst = [[1, 2], [3, 4], [5]]
print(flatten(nested_lst))  # Output: [1, 2, 3, 4, 5]


[1, 2, 3, 4, 5]


In [12]:
#Accessing Nested List Elements:

def access_nested_element(lst, indices):
    """
    Function to access a specific element from a nested list given its indices.
    
    Parameters:
    lst (list): A nested list of elements.
    indices (list): A list of indices to access the nested elements.
    
    Returns:
    The element located at the specified indices in the nested list.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element

nested_lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
print(access_nested_element(nested_lst, indices))  # Output: 6



6


In [13]:
# Sum of All Elements in a Nested List:

def sum_nested(lst):
    """
    Function to calculate the sum of all the numbers in a nested list (regardless of depth).
    
    Parameters:
    lst (list): A nested list of elements.
    
    Returns:
    int: The sum of all elements in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively sum sublist
        else:
            total += item
    return total

nested_lst = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested_lst))  # Output: 21


21


In [14]:
#Remove Specific Element from a Nested List:

def remove_element(lst, elem):
    """
    Function to remove all occurrences of a specific element from a nested list.
    
    Parameters:
    lst (list): A nested list of elements.
    elem (int/float/str): The element to remove.
    
    Returns:
    list: The modified list with all occurrences of elem removed.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))  # Recursively process sublist
        else:
            if item != elem:
                result.append(item)
    return result

nested_lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
print(remove_element(nested_lst, elem))  # Output: [[1], [3], [4, 5]]



[[1], [3], [4, 5]]


In [15]:
#Find the Maximum Element in a Nested List:

def find_max(lst):
    """
    Function to find the maximum element in a nested list (regardless of depth).
    
    Parameters:
    lst (list): A nested list of elements.
    
    Returns:
    The maximum element in the nested list.
    """
    max_element = float('-inf')  # Initialize to negative infinity
    for item in lst:
        if isinstance(item, list):
            max_element = max(max_element, find_max(item))  # Recursively find max in sublist
        else:
            max_element = max(max_element, item)
    return max_element

nested_lst = [[1, 2], [3, [4, 5]], 6]
print(find_max(nested_lst))  # Output: 6


6


In [16]:
#Count Occurrences of an Element in a Nested List:

def count_occurrences(lst, elem):
    """
    Function to count how many times a specific element appears in a nested list.
    
    Parameters:
    lst (list): A nested list of elements.
    elem (int/float/str): The element whose occurrences need to be counted.
    
    Returns:
    int: The number of occurrences of elem in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count occurrences in sublist
        else:
            if item == elem:
                count += 1
    return count

nested_lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
print(count_occurrences(nested_lst, elem))  # Output: 3



3


In [17]:
#Flatten a List of Lists of Lists:

def deep_flatten(lst):
    """
    Function to flatten a list of lists of lists into a single list, regardless of the depth.
    
    Parameters:
    lst (list): A deeply nested list of elements.
    
    Returns:
    list: A single flattened list.
    """
    flattened = []
    for item in lst:
        if isinstance(item, list):
            flattened.extend(deep_flatten(item))  # Recursively flatten sublist
        else:
            flattened.append(item)
    return flattened

nested_lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(nested_lst))  # Output: [1, 2, 3, 4, 5, 6, 7, 8]


[1, 2, 3, 4, 5, 6, 7, 8]


In [18]:
#Nested List Average:

def average_nested(lst):
    """
    Function to calculate the average of all elements in a nested list.
    
    Parameters:
    lst (list): A nested list of elements.
    
    Returns:
    float: The average of all elements in the nested list.
    """
    total = 0
    count = 0
    
    # Traverse the list recursively and calculate sum and count
    def traverse(lst):
        nonlocal total, count
        for item in lst:
            if isinstance(item, list):
                traverse(item)  # Recursively traverse sublist
            else:
                total += item
                count += 1
    
    traverse(lst)
    return total / count if count > 0 else 0  # Avoid division by zero if list is empty

nested_lst = [[1, 2], [3, 4], [5, 6]]
print(average_nested(nested_lst))  # Output: 3.5



3.5


# Numpy

Problem - 1: Array Creation


In [19]:
import numpy as np
empty_array = np.empty((2, 2))
print(empty_array)


[[4.94065646e-324 0.00000000e+000]
 [6.95288632e-310 0.00000000e+000]]


In [20]:
ones_array = np.ones((4, 2))
print(ones_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [21]:
ones_array = np.ones((4, 2))
print(ones_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
existing_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(existing_array)
print(zeros_like_array)


[[0 0]
 [0 0]]


In [23]:
ones_like_array = np.ones_like(existing_array)
print(ones_like_array)


[[1 1]
 [1 1]]


In [24]:
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print(np_array)


[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array Indexing

In [25]:
arr = np.arange(10, 50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [26]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print(mean_value)


0.48613701996225145


In [29]:
random_array_10x10 = np.random.random((10, 10))
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()
print("Min:", min_value, "Max:", max_value)


Min: 0.0050295073029749116 Max: 0.9879148680394434


In [30]:
zero_array = np.zeros(10)
zero_array[4] = 1  # Indexing is 0-based, so 5th element is index 4
print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [31]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)


[0 4 0 0 2 1]


In [32]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations


In [35]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

sum_array = x + y
print(sum_array)


[[ 6  8]
 [10 13]]


In [36]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

diff_array = x - y
print(diff_array)



[[-4 -4]
 [-4 -3]]


In [37]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

multiplied_array = x * 3  # Multiply x by 3 as an example
print(multiplied_array)


[[ 3  6]
 [ 9 15]]


In [38]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

squared_array = np.square(x)
print(squared_array)


[[ 1  4]
 [ 9 25]]


In [39]:
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:", dot_xv)
print("Dot product of x and y:", dot_xy)


Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


In [46]:


concatenated_xy = np.concatenate((x, y), axis=1)  # Concatenate along columns
concatenated_vw = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)  # Concatenate along row
print("Concatenated x and y along row:", concatenated_xy)
print("Concatenated v and w along column:", concatenated_vw)


Concatenated x and y along row: [[1 2 5 6]
 [3 5 7 8]]
Concatenated v and w along column: [[ 9 11]
 [10 12]]


Problem - 4: Matrix Operations

In [48]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1 = I:\n", identity_matrix)



A * A^-1 = I:
 [[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]


In [49]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

product_ab = np.dot(A, B)
product_ba = np.dot(B, A)
print("AB =\n", product_ab)
print("BA =\n", product_ba)




AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


In [50]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

transposed_ab = np.transpose(np.dot(A, B))
transposed_ba = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T = B^T A^T:\n", transposed_ab)
print("B^T A^T =\n", transposed_ba)


(AB)^T = B^T A^T:
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]


In [53]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Solve for X = A^-1 * B
X = np.linalg.inv(A).dot(B)
print("Solution (x, y, z):", X)


Solution (x, y, z): [ 2.  1. -2.]


In [54]:
solution = np.linalg.inv(A).dot(B)
print("Solution using np.linalg.inv:", solution)


Solution using np.linalg.inv: [ 2.  1. -2.]
